import { expect, test } from './fixtures'

test('featured route loads the actual GLB and supports camera controls', async ({ page }) => {
  let modelRequests = 0
  page.on('request', request => { if (request.url().includes('.glb')) modelRequests++ })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Transact', exact: true })).toBeVisible()
  expect(modelRequests).toBe(0)
  await page.getByRole('button', { name: 'Featured product', exact: true }).click()
  await expect(page).toHaveURL('/product')
  await expect(page.getByRole('heading', { name: 'Turbofan engine', exact: true })).toBeVisible()
  await expect(page.getByText('LIVE VIEW', { exact: true })).toBeVisible({ timeout: 25_000 })
  expect(modelRequests).toBeGreaterThan(0)
  const viewer = page.locator('model-viewer')
  await expect.poll(() => viewer.evaluate((element: any) => element.loaded && element.modelIsVisible)).toBe(true)
  await expect.poll(() => viewer.evaluate((element: any) => element.availableAnimations)).toContain('Fan spin')
  await expect.poll(() => viewer.evaluate((element: any) => element.paused)).toBe(false)
  const animationTime = await viewer.evaluate((element: any) => element.currentTime)
  await expect.poll(() => viewer.evaluate((element: any) => element.currentTime)).not.toBe(animationTime)
  await page.getByRole('button', { name: 'Spin fan blades', exact: true }).click()
  await expect.poll(() => viewer.evaluate((element: any) => element.paused)).toBe(true)
  const pausedTime = await viewer.evaluate((element: any) => element.currentTime)
  await page.getByRole('button', { name: 'Side', exact: true }).click()
  expect(await viewer.evaluate((element: any) => element.currentTime)).toBe(pausedTime)
  await page.getByRole('button', { name: 'Spin fan blades', exact: true }).click()
  await expect.poll(() => viewer.evaluate((element: any) => element.paused)).toBe(false)
  await page.getByRole('button', { name: 'Side', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Side', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect.poll(() => viewer.evaluate((element: any) => Math.round(element.getCameraOrbit().theta * 180 / Math.PI))).toBe(0)
  const radius = await viewer.evaluate((element: any) => element.getCameraOrbit().radius)
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect.poll(() => viewer.evaluate((element: any) => element.getCameraOrbit().radius)).toBeLessThan(radius)
  await page.getByRole('button', { name: 'Auto-rotate model', exact: true }).click()
  await expect.poll(() => viewer.evaluate((element: any) => element.autoRotate)).toBe(true)
  await page.getByRole('button', { name: 'Auto-rotate model', exact: true }).click()
  await expect.poll(() => viewer.evaluate((element: any) => element.autoRotate)).toBe(false)
  await page.getByRole('button', { name: 'Reset model view', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Perspective', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Use light background', exact: true }).click()
  await expect(page.locator('.product-stage')).toHaveClass(/light-stage/)
  if (await page.evaluate(() => document.fullscreenEnabled)) {
    await page.getByRole('button', { name: 'View fullscreen', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Exit fullscreen', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Exit fullscreen', exact: true }).click()
    await expect(page.getByRole('button', { name: 'View fullscreen', exact: true })).toBeVisible()
  }
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Download 3D model', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('turbofan-engine.glb')
  expect(await download.failure()).toBeNull()
  await page.getByRole('button', { name: 'Overview', exact: true }).click()
  await expect(page.locator('model-viewer')).toHaveCount(0)
  await page.goBack()
  await expect(page.getByText('LIVE VIEW', { exact: true })).toBeVisible()
})

test('failed model loads show a retry that recovers', async ({ page }) => {
  await page.route('**/*.glb*', route => route.fulfill({ status: 404, body: 'Model unavailable' }))
  await page.goto('/product')
  await expect(page.getByRole('alert')).toContainText('The model couldn’t be displayed.', { timeout: 25_000 })
  await expect(page.getByRole('button', { name: 'Side', exact: true })).toBeDisabled()
  await page.unroute('**/*.glb*')
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByText('LIVE VIEW', { exact: true })).toBeVisible({ timeout: 25_000 })
})

for (const width of [390, 768, 1440]) {
  test(`featured model renders and fits at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/product/')
    await expect(page.getByText('LIVE VIEW', { exact: true })).toBeVisible({ timeout: 25_000 })
    await expect(page.getByRole('link', { name: 'blenderbirb', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.getByRole('button', { name: 'Front', exact: true }).click()
    await expect.poll(() => page.locator('model-viewer').evaluate((element: any) => Math.round(element.getCameraOrbit().theta * 180 / Math.PI))).toBe(90)
    await page.getByRole('button', { name: 'Perspective', exact: true }).click()
    await expect.poll(() => page.locator('model-viewer').evaluate((element: any) => Math.round(element.getCameraOrbit().theta * 180 / Math.PI))).toBe(35)
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
    await page.screenshot({ path: `artifacts/product-${width}.png`, fullPage: true })
  })
}
