import { expect, test } from './fixtures'

test('workspace controls work without a wallet', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Transact', exact: true })).toBeVisible()
  await expect(page.getByText('Demo portfolio balance')).toBeVisible()
  const chart = page.locator('.chart-line')
  const originalPath = await chart.getAttribute('d')
  await page.getByRole('button', { name: '1M', exact: true }).click()
  await expect(chart).not.toHaveAttribute('d', originalPath!)
  await page.getByRole('tab', { name: 'Receive' }).click()
  await expect(page.getByRole('heading', { name: 'Your next destination.' })).toBeVisible()
  await page.getByRole('tab', { name: 'Swap' }).click()
  await expect(page.getByRole('button', { name: 'Connect wallet to swap' })).toBeEnabled()
  await page.getByRole('combobox', { name: 'Transaction network' }).selectOption('bitcoin')
  await expect(page.getByRole('button', { name: 'Connect wallet to swap' })).toBeDisabled()
  await page.getByRole('tab', { name: 'Send' }).click()
  await expect(page.getByRole('combobox', { name: 'Asset to send' })).toHaveValue('BTC')
  await page.getByRole('button', { name: 'Preferences', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('switch', { name: 'Hide balances' }).check()
  await page.getByRole('switch', { name: 'Show test networks' }).uncheck()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.locator('.portfolio-value h2')).toHaveText('••••••')
  await expect(page.getByRole('combobox', { name: 'Transaction network' }).locator('option')).toHaveCount(3)
  await page.getByRole('button', { name: 'Show balances' }).click()
  await page.getByRole('button', { name: 'View all' }).click()
  await expect(page.getByRole('heading', { name: 'Every move. On record.' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Search transactions' }).fill('USDC')
  await expect(page.locator('.activity-row')).toHaveCount(1)
  await page.getByRole('button', { name: 'Pending', exact: true }).click()
  await expect(page.getByText('No transactions match this filter.')).toBeVisible()
  await page.getByRole('button', { name: 'Networks', exact: true }).click()
  await expect(page.locator('.network-card')).toHaveCount(3)
  await page.getByRole('button', { name: 'Transact', exact: true }).nth(2).click()
  await expect(page.getByRole('combobox', { name: 'Transaction network' })).toHaveValue('bitcoin')
  await expect(page.getByText('Demo portfolio balance')).toBeVisible()
  expect(errors).toEqual([])
})

test('native AppKit connect modal opens', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Connect wallet', exact: true }).click()
  await expect(page.locator('w3m-modal')).toBeVisible()
  await expect(page.locator('w3m-modal').getByText('Connect Wallet', { exact: true })).toBeVisible()
})

test('dev defaults include both testnets independently of the production preference', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('block.testnets', 'false'))
  await page.goto('/')
  const network = page.getByRole('combobox', { name: 'Transaction network' })
  await expect(network.locator('option')).toHaveCount(5)
  for (const [key, symbol] of [['sepolia', 'ETH'], ['amoy', 'POL']] as const) {
    await network.selectOption(key)
    await expect(page.getByRole('combobox', { name: 'Asset to send' })).toHaveValue(symbol)
    await expect(page.getByRole('button', { name: 'Token amount', exact: true })).toBeEnabled()
    await expect(page.locator('.mode-label')).toContainText('TESTNET')
    await page.getByRole('tab', { name: 'Swap' }).click()
    await expect(page.getByRole('button', { name: 'Connect wallet to swap' })).toBeDisabled()
    await page.getByRole('tab', { name: 'Send' }).click()
  }
  await page.getByRole('button', { name: 'Networks', exact: true }).click()
  await expect(page.locator('.network-card')).toHaveCount(5)
  await expect(page.getByRole('heading', { name: 'Sepolia', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Polygon Amoy', exact: true })).toBeVisible()
})

for (const width of [390, 768, 1024, 1440]) {
  test(`layout fits ${width}px viewport`, async ({ page }) => {
    await page.setViewportSize({ width, height: 844 })
    await page.goto('/')
    await expect(page.getByRole('heading', { name: 'Transact', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.getByRole('tab', { name: 'Receive' }).click()
    await expect(page.getByRole('button', { name: 'Connect wallet to receive' })).toBeVisible()
    await page.screenshot({ path: `artifacts/workspace-${width}.png`, fullPage: true })
  })
}
